### ISSUE TITLE
User should only be retrieved once from database

### ISSUE THREAD

**Issue by aakil786** [grassrootza/grassroot-platform#32]
after logon rest of the user interaction we should never have to fetch the user and associated links from the database again. if groups are added/removed after the db is updated the session user should be replaced, so that it is current.

if not session then   ehcache. Currently the most work the system is doing is fetching the user and it's roles and groups, this alone makes up 50% of database activity during the following workflow.

1. user login
2. create a vote
3. return to home
4. vote 
5. re-display of home

changing the onetomany relationships to fetch=lazy helped a little but we are still fetching the user over and over again, when working in the web.

For USSD one could argue that maybe there is no session, and then maybe it should be moved to ehcache

**Comment by luke-grassroot** [comment]
One note on this -- as you note, in USSD menus we do not have a session, and so we have to retrieve the user on almost every menu. So, we should definitely move that to ehcache -- it seems okay within the menus themselves, since those are so light on data, but will start hitting overall database performance I'm sure.

The method we almost always use in USSD menus is userManagementService.loadOrSaveUser and .findByInputNumber. Both are passed phone numbers.
