### ISSUE TITLE
Means to send 'system' messages, e.g., to new users

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#39]
Need a way to send a simple couple of reference SMSs to users shortly after they initiate their first session.

This should not send to users only after they are created as an entity, since that occurs just if they are added to a group, and this may confuse people / look like spam. But we have a method "setInitiatedSession" which could trigger this / add it to a queue.

Timing should be roughly 5-15 minutes after first use, but does not need to be exact for all users, i.e., can be sent in batches at certain time intervals.

**Comment by aakil786** [comment]
used the setInitiatedSession to trigger the welcome messages. there will be a delay between 0 and 15 minutes as the scheduled task that sends the message will run every 15 minutes.

Luke to create the welcome messages in the messages property files and then enable them by setting the values in EventNotificationConsumer 

   /*
    change this to add messages or stop messages altogether by leaving it empty.
     */
    private final String[] welcomeMessages = new String[] {
    };

/*
    private final String[] welcomeMessages = new String[] {
            "sms.welcome.1",
            "sms.welcome.2"
    };
*/

the messages sent are not stored anywhere, something to think about.
Also at some point we need to start externalizing the config so that changes can be made without code changes and deployment.
